#!/bin/bash
# Script Name: breaches_per_month
# Author: warren wang
# Creation Date: 2023-05-18

# display usage instructions
function incidisplay_help_func() {
    echo "Usage: $0 [file]"
    echo
    echo "Example:"
    echo "  $0 Cyber_Security_Breaches_clean.tsv"
}

#  check: input arguments
function check_file_func() {
    if [ $# -eq 0 ]; then
        echo "No arguments input. Please input the file name."
        incidisplay_help_func
        exit 1
    fi
}

# caculate incidents of per month
function calculate_incidents_func() {
    tail -n +2 $1 | awk -F'\t' '{print $6}' | \
    sort | uniq -c | sort -k1n
}

# calculate median of all months
function calculate_median_func() {
    echo "$1" | awk '{
        arr[NR]=$1
    } END {
        if(NR%2==1) 
            print arr[(NR+1)/2]
        else 
            print (arr[(NR/2)]+arr[(NR/2)+1])/2
    }'
}

# calculate MAD
function calculate_mad_func() {
    echo "$1" | awk -v median=$2 '{
        arr[NR]=($1-median>=0)?$1-median:median-$1
    } END {
        for(i=1;i<=NR;i++) 
            print arr[i]
    }' | sort -n | awk '{
        arr[NR]=$1
    } END {
        if(NR%2==1) 
            print arr[(NR+1)/2]
        else 
            print (arr[(NR/2)]+arr[(NR/2)+1])/2
    }'
}

# print results
function print_results_func() {
    echo -e "Month\tIncidents\tStatus"
    echo "-----------------------------------"

    for i in {1..12}
    do
        incidents=$(echo "$1" | awk -v month=$i '$2==month {print $1}')
        
        if [ -z "$incidents" ]; then incidents=0; fi
        
        month_name=$(date -d "2000-$i-01" '+%b')
        
        printf "%s\t%s\t" $month_name $incidents
        
        if (( $(echo "$incidents > $2 + $3" | bc -l) )); then
            echo "++"
        elif (( $(echo "$incidents < $2 - $3" | bc -l) )); then
            echo "--"
        else
            echo
        fi
    done
}

# define main function
function main() {
    check_file_func "$@"
    
    local file=$1
    
    local incidents_of_per_month=$(calculate_incidents_func $file)
    
    local median=$(calculate_median_func "$incidents_of_per_month")
    
    local mad=$(calculate_mad_func "$incidents_of_per_month" $median)

    echo "Median: $median"
    echo "MAD: $mad"
    echo 
    print_results_func "$incidents_of_per_month" $median $mad
}

# call main func
main "$@"
